/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ManageState;

import Business.City.City;
import Business.Country.Country;
import Business.Request.Request;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.WHO;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VAIBHAV RAJ
 */
public class StateAllRequestJPanel extends javax.swing.JPanel {
    
    HashMap<Integer,Request> requestList;
 
    JPanel userProcessContainer;
    Country country;
    City city;
    State state;
    UserAccount account;

    /**
     * Creates new form StateAllRequestJPanel
     */
    public StateAllRequestJPanel(JPanel userProcessContainer, UserAccount account,City city, 
            State state,
            Country country,
            WHO business)
     {
        initComponents();
        this.userProcessContainer=userProcessContainer;
       
        this.requestList=state.getRequestList();
        this.country = country;
        this.city = city;
        this.state = state;
        this.account = account;
        cityList.addItem("All");
       populateCityList();
       // populatNewRequestTable();
        displayList();
     }

    private void populateCityList()
    {
        for(City city:state.getCityDirectory().getCityList())
            cityList.addItem(city);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StateRequestJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        cityList = new javax.swing.JComboBox();
        viewRequest = new javax.swing.JButton();
        statusList = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(210, 215, 211));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 110, 123));
        jLabel1.setText("Requests Under Queue Of State");

        StateRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RequestNo", "Name", "Date", "Status", "Email Id", "City", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(StateRequestJTable);

        backJButton.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        backJButton.setForeground(new java.awt.Color(31, 58, 147));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        cityList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityListActionPerformed(evt);
            }
        });

        viewRequest.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        viewRequest.setForeground(new java.awt.Color(52, 73, 94));
        viewRequest.setText("View Request");
        viewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestActionPerformed(evt);
            }
        });

        statusList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "New Request", "Working Request", "Proposal", "Reverted", "Accepted", "Built", "Rejected" }));
        statusList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(backJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewRequest)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cityList, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusList, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(viewRequest))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cityListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityListActionPerformed
        // TODO add your handling code here:
        
//        if(cityList.getSelectedIndex()>0)
//        {
//        populateCityRequestTable((City)cityList.getSelectedItem());
//        }
//        else
//        {
//            populatNewRequestTable();
//        }
        displayList();
    }//GEN-LAST:event_cityListActionPerformed

    public void checkSelectedNode()
    {
//         if(cityList.getSelectedIndex()>0)
//        {
//        populateCityRequestTable((City)cityList.getSelectedItem());
//        }
//        else
//        {
//            populatNewRequestTable();
//        }
        displayList();
    }
    private void viewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestActionPerformed
        // TODO add your handling code here:
        if(StateRequestJTable.getSelectedRow()>=0)
        {
            Request req=(Request)StateRequestJTable.getValueAt(StateRequestJTable.getSelectedRow(),0);
            ManagerStateRequestViewJPanel mcvjp = new ManagerStateRequestViewJPanel(userProcessContainer, req);
            userProcessContainer.add(mcvjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
                
        }
        
    }//GEN-LAST:event_viewRequestActionPerformed

    private void statusListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusListActionPerformed
        // TODO add your handling code here:
        displayList();
        
        
    }//GEN-LAST:event_statusListActionPerformed

    public void displayList()
    {
              ArrayList<Request> reqList=new ArrayList<>();
        if(cityList.getSelectedIndex()==0)
        {
         reqList.addAll(state.getRequestList().values());
        }
        else
        {
            reqList.addAll(((City)cityList.getSelectedItem()).getRequestList().values());
        }
        
        int status=statusList.getSelectedIndex();
        
        reqList=getRequestListBasedOnStatus(reqList,status);
        if(reqList!=null)
        {
                DefaultTableModel model = (DefaultTableModel) StateRequestJTable.getModel();
        
        model.setRowCount(0);
                DefaultTableModel model1 = (DefaultTableModel) StateRequestJTable.getModel();
        
        model1.setRowCount(0);
        
        for (Request request : reqList)
        {

            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getRequestor().getRequestorName();
            row[2]=request.getDateTime();
            row[3] = request.getStatus();
            row[4] = request.getRequestor().getRequestorEmail();
            
            row[5] = request.getCity();
            
            row[6] = request.getRequestor().getRequestorPhoneNumber();
            model.addRow(row);
            
          
     }
        }
    }
private ArrayList<Request> getRequestListBasedOnStatus(ArrayList<Request> reqList,int status)
{
    ArrayList<Request> updatedReqList=new ArrayList<Request>();
    if(status==1)
    {
        for(Request req:reqList)
        {
            if(req.getStatus().getStatusId()==0)
            {
            updatedReqList.add(req);
            }
        }
    }
    else if(status==2)
    {
        for(Request req:reqList)
        {
            if(req.getStatus().getStatusId()>0 && req.getStatus().getStatusId()<5)
            {
            updatedReqList.add(req);
            }
        }
    }
    else if(status==3)
    {
        for(Request req:reqList)
        {
            if(req.getStatus().getStatusId()==5)
            {
            updatedReqList.add(req);
            }
        }
    }
        else if(status==4)
    {
        for(Request req:reqList)
        {
            if(req.getStatus().getStatusId()>5 && req.getStatus().getStatusId()<9)
            {
            updatedReqList.add(req);
            }
        }
    }
        else if(status==5)
    {
        for(Request req:reqList)
        {
            if(req.getStatus().getStatusId()==9)
            {
            updatedReqList.add(req);
            }
        }
    }
        else if(status==6)
    {
        for(Request req:reqList)
        {
            if(req.getStatus().getStatusId()==10)
            {
            updatedReqList.add(req);
            }
        }
    }
            else if(status==7)
    {
        for(Request req:reqList)
        {
            if(req.getStatus().getStatusId()==11)
            {
            updatedReqList.add(req);
            }
        }
    }
    else
                updatedReqList=reqList;
    return updatedReqList;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StateRequestJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox cityList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox statusList;
    private javax.swing.JButton viewRequest;
    // End of variables declaration//GEN-END:variables

    private void populatNewRequestTable() {
        
         DefaultTableModel model = (DefaultTableModel) StateRequestJTable.getModel();
        
        model.setRowCount(0);
                DefaultTableModel model1 = (DefaultTableModel) StateRequestJTable.getModel();
        
        model1.setRowCount(0);
        
        for (Request request : requestList.values())
        {

            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getRequestor().getRequestorName();
            row[2]=request.getDateTime();
            row[3] = request.getStatus();
            row[4] = request.getRequestor().getRequestorEmail();
            
            row[5] = request.getCity();
            
            row[6] = request.getRequestor().getRequestorPhoneNumber();
            model.addRow(row);
            
          
     }
    }
     private void populateCityRequestTable(City city) {
        
         DefaultTableModel model = (DefaultTableModel) StateRequestJTable.getModel();
        
        model.setRowCount(0);
                DefaultTableModel model1 = (DefaultTableModel) StateRequestJTable.getModel();
        
        model1.setRowCount(0);
        
        for (Request request : city.getRequestList().values())
        {

            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getRequestor().getRequestorName();
            row[2]=request.getDateTime();
            row[3] = request.getStatus();
            row[4] = request.getRequestor().getRequestorEmail();
            
            row[5] = request.getCity();
            
            row[6] = request.getRequestor().getRequestorPhoneNumber();
            model.addRow(row);
            
          
     }
    }
}
